# Generated by Django 4.1.4 on 2023-01-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musiclist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(default='', max_length=100)),
                ('song_date', models.DateField(default='')),
                ('song_details', models.CharField(default='', max_length=500)),
                ('song', models.FileField(default='', upload_to='')),
                ('song_coverimage', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
